language: python
install:
  - pip install pytest
  - pip install pytest-cov
  - pip install -r requirements.txt
  - pip install -e .
python:
  - "3.5"
  - "3.6"
script:
  - pytest --cov ./
after_success:
  - codecov
